# Time Machine Theme Configuration
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme

# Site Configuration
title: Steve Regester
description: Innovative Full-Stack Engineer specializing in enhancing user experiences and building secure, scalable SaaS platforms.
url: https://egeste.net
baseurl: 

# Theme Options
show_downloads: false

# Google Analytics
google_analytics: UA-25824741-1

# Build settings
markdown: kramdown

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/