# Custom Theme Configuration
plugins:
- jekyll-feed
- jekyll-sitemap

# Site Configuration
title: Steve Regester
description: Visionary Engineering Leader & Full-Stack Architect | 15+ years scaling teams & transformative SaaS platforms | Co-founded startup • Achieved SOC 2 • 60%+ engagement gains • Expert in React, Node.js, AWS
url: https://egeste.net
baseurl:

# Theme Options
show_downloads: false


# Build settings
markdown: kramdown

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/