# Site
url: 'http://egeste.net'
bio: 'Software Engineering and Other Stuff'
title: 'Steve Regester'
locale: en_US
baseurl: '/'
description: 'Senior Software Engineer, Synack'

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: '/blog/:title/'
    layout: post
    author:

# Jekyll
mathjax: true
markdown: kramdown
permalink: /blog/:title/
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..6
  footnote_nr: 1
  entity_output: as_char
  enable_coderay: false
sass:
  style: compressed
  sass_dir: _sass

# Comments
disqus_shortname: default

# Social
github: egeste
twitter: egeste
facebook: egeste
analytics-id: UA-25824741-1

# personal
email: 'nospam@egeste.net'
phone: '+1 (415) 967 - 0990'
location: 'Greater Seattle Area'

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: '/blog/page:num/'

jekyll-mentions:
  base_url: https://github.com

# Exclude list
exclude: [
  README.md,
  Gemfile,
  Gemfile.lock,
  node_modules,
  gulpfile.js,
  package.json,
  _site,
  src,
  vendor,
  CNAME,
  LICENSE,
  Rakefile,
  old
]
