# Site settings
url: 'http://egeste.net'
baseurl: '/'

title: 'Steve Regester'
description: 'Senior Software Engineer • Lookout'

google_analytics: 'UA-25824741-1'
disqus_shortname: 'egeste-net'

author:
  name: 'Steve Regester'
  email: 'nospam@egeste.net'
  github_username: 'egeste'
  twitter_username: 'egeste'
  linkedin_username: 'egeste'
  # facebook_username: egeste

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
paginate: 10
markdown: kramdown
permalink: /:year/:title/
highlighter: rouge
destination: _site

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
