# ===== JEKYLL PLUGINS =====
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# ===== SITE CONFIGURATION =====
title: Steve Regester - Technology Consulting & Engineering Leadership
tagline: Startup Consulting, Full-Stack Engineering, Automation & Security
description: >-
  Expert technology consulting services for growing businesses. 15+ years of experience in startup 
  development, full-stack engineering, business automation, and security testing. Serving businesses 
  nationwide with founding engineer services, CTO consulting, custom development, and technical leadership.

url: https://egeste.net
baseurl: ""
lang: en_US
timezone: America/Los_Angeles

# ===== AUTHOR & PERSONAL INFO =====
author:
  name: Steve Regester
  first_name: Steve
  last_name: Regester
  username: egeste
  email: info@egeste.net
  bio: >-
    Technology consultant and engineering leader with 15+ years of experience helping businesses grow 
    through expert technical guidance. Specializing in startup consulting, full-stack engineering, 
    business automation, and security testing.
  location: Portland, Oregon, United States
  avatar: /assets/images/avatar.jpg
  website: https://egeste.net
  
  # Social profiles
  twitter: egeste
  linkedin: egeste
  github: egeste
  
  # Professional details
  job_title: Technology Consultant & Engineering Leader
  company: Independent Consultant
  skills:
    - Startup Consulting
    - Full-Stack Engineering
    - Business Automation
    - Security Testing
    - CTO Consulting
    - Technical Leadership
    - React & Node.js
    - AWS & Cloud Architecture

# ===== SOCIAL PROFILES FOR STRUCTURED DATA =====
social:
  name: Steve Regester
  email: "info@egeste.net"
  linkedin: "https://linkedin.com/in/egeste"
  github: "https://github.com/egeste"
  website: "https://egeste.net"
  
  # Keep the links array for structured data compatibility
  links:
    - https://linkedin.com/in/egeste
    - https://github.com/egeste
    - https://egeste.net
    - mailto:info@egeste.net

# ===== SEO & METADATA =====
logo: /assets/images/favicon.svg
image: /assets/images/og-banner.png

# OpenGraph defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
      author: Steve Regester
      image: /assets/images/og-banner.png
      type: website
      
  - scope:
      path: "index.md"
    values:
      priority: 1.0
      changefreq: weekly
      type: profile
      
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      type: article
      priority: 0.8
      changefreq: monthly
      
# SEO tag settings
twitter:
  username: egeste
  card: summary_large_image 

# ===== ANALYTICS & VERIFICATION =====
# google_analytics: GA_MEASUREMENT_ID
# google_site_verification: VERIFICATION_CODE
# bing_site_verification: VERIFICATION_CODE

  
# ===== PROFESSIONAL DATA =====
professional:
  # Current Position
  current_company: "Delphos Labs"
  current_role: "Staff Software Engineer & Team Lead"
  
  # Career Context
  status: "Reversing binaries with AI @ https://delphoslabs.com"
  experience_years: "15+ years"
  location: "Portland, Oregon"
  
  # Job Preferences
  seeking_roles: ["Staff Engineer", "Principal Engineer", "Director of Engineering", "Founding Engineer"]
  work_locations: ["Portland, Oregon", "Remote"]
  company_types: ["Early-stage startups", "Growth-stage companies", "Enterprise companies"]
  
  # Core Skills
  expert_technologies: ["React", "Node.js", "TypeScript", "Python", "AWS", "Docker"]
  key_skills: ["Technical Leadership", "Team Mentorship", "SaaS Architecture", "Full-Stack Development", "Engineering Excellence", "SOC 2 Compliance"]
  
  # Key Achievements
  achievements:
    - "60%+ User Engagement Growth through UI/UX transformations"
    - "SOC 2 Certification Achievement leading enterprise security"
    - "Doubled Security Research Productivity through tool development"
    - "50%+ Programming Error Reduction through training programs"
    - "20% Project Timeline Reduction through team leadership"
    
  # Work History
  work_history:
    - company: "Delphos Labs"
      role: "Staff Software Engineer & Team Lead"
      period: "current"
    - company: "Studylog Systems"
      role: "Director of Engineering"
      period: "2021-2024"
    - company: "Synack"
      role: "Senior Software Engineer II"
      period: "2016-2021"
    - company: "Lookout"
      role: "Senior Software Engineer & Team Lead"
      period: "2014-2016"
    - company: "Ultimatum"
      role: "Co-founder & CTO"
      period: "2012-2014"

# ===== SITE CONFIGURATION =====
site_config:
  primary_color: "#8b5cf6"
  contact_email: "info@egeste.net"
  geographic_region: "US-OR"
  city: "Portland"
  state: "Oregon"
  coordinates: "45.5152, -122.6784"

# ===== UI TEXT & LABELS =====
text:
  back_to_blog: "← Back to Blog"
  no_posts_message: "No posts yet. Check back soon!"
  skip_to_content: "Skip to main content"

navigation:
  home: "Home"
  about: "About"
  projects: "Projects"
  blog: "Blog"
  faq: "FAQ"
  contact: "Contact"

# ===== ACCESSIBILITY =====
accessibility:
  focus_color: "#0066cc"

# ===== FONTS =====
fonts:
  preconnect:
    - "https://fonts.googleapis.com"
    - "https://fonts.gstatic.com"
  stylesheet: "https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;600;700;800;900&family=Exo:wght@300;400;500;600;700&family=Audiowide&family=Rajdhani:wght@300;400;500;600;700&family=JetBrains+Mono:ital,wght@0,400;0,500;0,600;1,400&display=swap"
  primary: "Orbitron"
  secondary: "Exo"
  accent: "Audiowide"
  monospace: "JetBrains Mono"

# ===== ANIMATIONS =====
mesh_animation:
  max_nodes: 64
  max_distance: 256
  colors:
    user_created: "6, 182, 212"
    default: "139, 92, 246"

# ===== PWA MANIFEST =====
manifest:
  start_url: "/"
  display: "standalone"
  background_color: "#1a1a2e"
  orientation: "portrait-primary"
  scope: "/"
  dir: "ltr"
  categories: ["business", "productivity", "professional"]
  icons:
    - src: "/assets/images/favicon.svg"
      sizes: "any"
      type: "image/svg+xml"
      purpose: "any maskable"
    - src: "/assets/images/apple-touch-icon.png"
      sizes: "180x180"
      type: "image/png"
      purpose: "any"
    - src: "/assets/images/favicon-32x32.png"
      sizes: "32x32"
      type: "image/png"
      purpose: "any"
    - src: "/assets/images/favicon-16x16.png"
      sizes: "16x16"
      type: "image/png"
      purpose: "any"
  screenshots:
    - sizes: "1200x630"
      type: "image/png"
  related_applications: []
  prefer_related_applications: false
  edge_side_panel:
    preferred_width: 480
  launch_handler:
    client_mode: "navigate-existing"

# ===== SEO SETTINGS =====
seo:
  robots_content: "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1"
  ai_content_declaration: "human-authored"
  schema_types: ["Person", "SoftwareEngineer"]
  
# ===== CONTENT & SEO =====
content_settings:
  categories: ["Engineering Leadership", "Technical Architecture", "Team Management", "Software Development"]
  target_audience: "technical-recruiters,engineering-leaders,startup-founders"
  content_type: "professional-portfolio"
  last_update: "2024-07"

# ===== TECHNICAL CONFIGURATION =====
# Feed settings
feed:
  posts_limit: 20
  excerpt_only: false

# Sitemap settings
sitemap:
  priority: 1.0
  changefreq: monthly
  lastmod: true

# Performance
sass:
  style: compressed
  
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Theme Options
show_downloads: false


# Build settings
markdown: kramdown

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - context/