# Custom Theme Configuration
plugins:
- jekyll-feed
- jekyll-sitemap

# Site Configuration
title: Steve Regester
description: Staff Software Engineer & Engineering Leader | 15+ years architecting transformative SaaS platforms | Expert in React, Node.js, AWS | Empathetic team leadership & quality-first engineering
url: https://egeste.net
baseurl:

# Theme Options
show_downloads: false


# Build settings
markdown: kramdown

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/